#!/bin/sh

# 创建 root 用户的 crontab 文件
touch /etc/crontabs/root

# 设置 LuCI 默认语言与主题
uci set luci.main.lang=zh_cn
uci set luci.main.mediaurlbase=/luci-static/bootstrap
uci commit luci

# 设置时区
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

# 启用自动挂载
uci set fstab.@global[0].anon_mount=1
uci commit fstab

# 创建 ip 命令软链接
ln -sf /sbin/ip /usr/bin/ip




# ✅ 自动替换 distfeeds.conf 为北京大学镜像源
arch=$(grep DISTRIB_ARCH /etc/openwrt_release | cut -d"'" -f2)
branch=$(grep DISTRIB_RELEASE /etc/openwrt_release | cut -d"'" -f2)
# mirror_base="http://mirrors.pku.edu.cn/immortalwrt/releases/$branch/packages/$arch"
mirror_base="https://mirrors.pku.edu.cn/openwrt/releases/$branch/packages/$arch"
# 例子：https://mirrors.pku.edu.cn/openwrt/releases/21.02.0/packages/aarch64_cortex-a53/base/

# 清空并写入新的源
cat > /etc/opkg/distfeeds.conf <<EOF
src/gz openwrt_base $mirror_base/base
src/gz openwrt_luci $mirror_base/luci
src/gz openwrt_packages $mirror_base/packages
src/gz openwrt_routing $mirror_base/routing
src/gz openwrt_telephony $mirror_base/telephony
EOF






# 设置 DHCP 为 IPv6 管理模式
uci set dhcp.lan.ra='server'
uci -q del dhcp.lan.dhcpv6
uci set dhcp.lan.dns_service='0'
uci set dhcp.lan.ra_management='1'
uci -q del dhcp.lan.ra_slaac
uci commit dhcp

# 启用 WiFi
sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

# 设置版本信息
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt 24.10'" >> /etc/openwrt_release

# 隐藏状态页默认视图
rm -rf /usr/lib/lua/luci/view/admin_status/index

# 替换主题 footer 中的 openwrt/luci 链接为 lienol/openwrt-luci
sed -i 's#openwrt/luci#lienol/openwrt-luci#g' /usr/lib/lua/luci/view/themes/*/footer.htm

# 禁用部分不必要服务
for svc in \
    php7-fastcgi php7-fpm \
    php8-fastcgi php8-fpm \
    softethervpnbridge softethervpnserver softethervpnclient \
    haproxy kcptun; do
    /etc/init.d/$svc disable 2>/dev/null
done

# 修改权限
chmod 0755 /etc/init.d/*

# 清除 Luci 缓存
rm -rf /tmp/luci-*cache

exit 0
