#!/bin/sh /etc/rc.common
START=99
STOP=13
USE_PROCD=1
service="$(basename ${basescript:-$initscript})"

extra_command "start_instance" "<modem_cfg> start led script for one modem"
extra_command "stop_instance" "<modem_cfg> stop led script for one modem"
extra_command "restart_instance" "<modem_cfg> restart led script for one modem"

service_triggers()
{
	procd_add_reload_trigger "qmodem"

}

start_service(){
    load_led_services
}

stop_service(){
    procd_kill "$service"
    config_load qmodem
    config_foreach _turn_off_leds modem-device
}

reload_service(){
    stop_service
    start_service
}

load_led_services()
{
    config_load qmodem
    config_foreach _led_services modem-device
}


_led_services()
{
    _start_instance "$1"
}

start_instance()
{
    [ -n "$1" ] || return 1
    config_load qmodem
    procd_kill "$service" "led_$1"
    rc_procd _start_instance "$1"
}

stop_instance()
{
    [ -n "$1" ] || return 1
    config_load qmodem
    procd_kill "$service" "led_$1"
    _turn_off_leds "$1"
}

restart_instance()
{
    stop_instance "$1"
    start_instance "$1"
}

_start_instance()
{
    local led_script
    config_get led_script "$1" led_script
    if [ -n "$led_script" ] && [ -x "/usr/share/qmodem/led_scripts/${led_script}.sh" ]; then
        procd_open_instance led_$1
        procd_set_param command "/usr/share/qmodem/led_scripts/${led_script}.sh" "$1"
        procd_set_param respawn 120 15 10
        procd_close_instance
    fi
}

_turn_off_leds(){
    local led_script
    config_get led_script "$1" led_script
    if [ -n "$led_script" ] && [ -x "/usr/share/qmodem/led_scripts/${led_script}.sh" ]; then
        /usr/share/qmodem/led_scripts/${led_script}.sh "$1" "off"
    fi
}