#!/bin/sh
# Copyright (C) 2024 Tom <fjrcn@outlook.com>
manual=$(uci -q get qmodem.main.block_auto_probe)
[ "${manual}" -eq 1 ] && exit

logger -t modem_hotplug "net slot: ${DEVPATH} action: ${ACTION}"
hotplug_add_delay=$(uci -q get qmodem.main.hotplug_add_delay || echo 8)
#网络设备名称不存在，退出
[ -z "${INTERFACE}" ] && exit
#网络设备路径不存在，退出
[ -z "${DEVPATH}" ] && exit

slot_path=$(readlink -f "/sys/${DEVPATH}/device")
[ -z "${slot_path}" ] && exit

slot=$(basename "$(dirname "${slot_path}")")

if [ -d "/sys/bus/usb/devices/${slot}" ]; then
    slot_type="usb"
elif [ -d "/sys/bus/pci/devices/${slot}" ]; then
    slot_type="pcie"
else
    exit
fi

logger -t modem_hotplug "net slot: ${slot} action: ${ACTION} slot_type: ${slot_type}"
case "${ACTION}" in
    add|\
    bind)
        (/usr/share/qmodem/modem_scan.sh add "${slot}" "${slot_type}" "${hotplug_add_delay}" >/dev/null 2>&1) &
        ;;
esac
