#!/bin/sh

. /lib/functions.sh
. /lib/functions/uci-defaults.sh
. /lib/functions/qmodem-defaults.sh

board_config_update

board="$(board_name)"

case "$board" in
arcadyan,aw1000)
	ucidef_add_qmodem_slot usb0 type usb slot 4-1 net_led 'ipq::led9' sim_led 'ipq::led2' alias wwan0
	ucidef_add_qmodem_slot pcie0 type pcie slot '0000:01:00.0' net_led 'ipq::led9' sim_led 'ipq::led2' associated_usb 4-1 alias wwan1
	;;
alwaylink,m60k63|\
feiyan,m60k63)
	ucidef_add_qmodem_slot wwan0 type usb slot 2-1 alias wwan0 gpio 5g-power gpio_up 0 gpio_down 1 default_metric 5
	ucidef_add_qmodem_modem_status modem_status enabled 1 script m60k63 bind port port 2-1
	;;
nradio,c2000-max)
	ucidef_add_qmodem_slot eth2 type usb slot 2-1 alias eth2
	ucidef_add_qmodem_modem_status modem_status enabled 1 script c2000_max bind port port 2-1
	;;
hiveton,h5000m)
	ucidef_set_qmodem_main enable_pcie_scan 0 start_delay 9
	ucidef_add_qmodem_slot usb0 type usb slot 2-1 alias USB
	;;
HC,HC-G80*)
	ucidef_add_qmodem_slot mini_pci type usb slot 1-1.4
	ucidef_add_qmodem_slot m2_u2 type usb slot 1-1.1 ethernet_5g cpewan0
	ucidef_add_qmodem_slot m2_u3 type usb slot 2-1 ethernet_5g cpewan0
	;;
huasifei,wh3000-pro)
	ucidef_add_qmodem_slot 5g0 type usb slot 2-1.4 alias wwan0 gpio modem_power gpio_up 0 gpio_down 1 default_metric 6
	;;
huasifei,ws1610)
	ucidef_add_qmodem_slot m2_0 type usb slot 2-1 alias m2_0 net_led green:5g sim_led green:sim1 gpio m2_reset_1 gpio_up 1 gpio_down 0 default_metric 5
	ucidef_add_qmodem_slot minipci_0 type usb slot 1-1 alias minipci_0 net_led green:5g sim_led green:sim2 default_metric 10
	;;
ailf,gs2410|\
huasifei,ws3006)
	ucidef_add_qmodem_slot 5g1 type usb slot 2-1.2 alias 5g1 net_led green:5g2 sim_led green:sim2 gpio m2_reset_2 gpio_up 1 gpio_down 0 default_metric 5
	ucidef_add_qmodem_slot 5g0 type usb slot 2-1.4 alias 5g0 net_led green:5g1 sim_led green:sim1 gpio m2_reset_1 gpio_up 1 gpio_down 0 default_metric 6
	ucidef_add_qmodem_slot 4g3 type usb slot 1-1.1 alias 4g3 net_led green:5g2 sim_led green:sim2 gpio m2_reset_2 gpio_up 1 gpio_down 0 default_metric 20
	ucidef_add_qmodem_slot 4g2 type usb slot 1-1.4 alias 4g2 net_led green:5g1 sim_led green:5g1 gpio m2_reset_1 gpio_up 1 gpio_down 0 default_metric 21
	ucidef_add_qmodem_slot 4g1 type usb slot 1-1.2 alias 4g1 net_led green:5g2 sim_led green:sim2 default_metric 22
	ucidef_add_qmodem_slot 4g0 type usb slot 1-1.3 alias 4g0 net_led green:5g1 sim_led green:sim1 default_metric 23
	;;
huasifei,ws3009)
	ucidef_add_qmodem_slot 5g1 type usb slot 2-1.2 alias 5g1 net_led green:network1 gpio m2_reset_1 gpio_up 1 gpio_down 0 default_metric 5
	ucidef_add_qmodem_slot 5g0 type usb slot 2-1.4 alias 5g0 net_led green:network2 gpio m2_reset_1 gpio_up 1 gpio_down 0 default_metric 6
	ucidef_add_qmodem_slot 5g2 type usb slot 2-1.1 alias 5g2 net_led green:network3 gpio m2_reset_2 gpio_up 1 gpio_down 0 default_metric 7
	ucidef_add_qmodem_slot 4g0 type usb slot 1-1.3 alias 4g0 net_led green:network1 default_metric 20
	ucidef_add_qmodem_slot 4g1 type usb slot 1-1.4 alias 4g3 net_led green:network2 default_metric 21
	ucidef_add_qmodem_slot 4g2 type usb slot 1-1.1 alias 4g4 net_led green:network3 default_metric 22
	;;
misectel,m01k43|\
misectel,m01k43-usb|\
misectel,m01k43-usb-p|\
misectel,m01k43-p|\
misectel,m02k45)
	usb_port=2-1
	pcie_port='0000:01:00.0'
	[ "$board" = 'misectel,m01k43-usb-p' ] && usb_port=2-1.1
	if [ "$board" = 'misectel,m02k45' ]; then
		pcie_port='0002:01:00.0'
	fi
	ucidef_set_qmodem_main start_delay 15
	ucidef_add_qmodem_slot usb0 type usb slot "$usb_port" alias wwan0 scan_priority pcie
	ucidef_add_qmodem_slot pcie0 type pcie slot "$pcie_port" associated_usb "$usb_port" alias pcie0 scan_priority pcie
	ucidef_add_qmodem_network_detect internet enabled 1 script misectel_network_detect
	ucidef_add_qmodem_modem_status cellular enabled 1 script misectel_modem_status bind any
	;;
p2w,r619ac*)
	ucidef_add_qmodem_slot minipcie type usb slot 3-1 alias wwan0 net_led blue:power default_metric 10
	;;
sagemcom,5866t)
	ucidef_add_qmodem_slot 5g_usb type usb slot 1-1 alias 5g_usb net_led LED5_G sim_led LED4_G default_metric 10
	ucidef_add_qmodem_slot 5g_pcie type pcie slot '0000:01:00.0' alias 5g_pcie net_led LED5_G sim_led LED4_G associated_usb 1-1 default_metric 10
	;;
cyber,cyber3588-aib)
	ucidef_add_qmodem_slot 5g_usb0 type usb slot 8-1 alias 5g_usb0 net_led blue:status sim_led green:status default_metric 10
	ucidef_add_qmodem_slot 5g_pcie0 type pcie slot '0001:11:00.0' alias 5g_pcie0 net_led blue:status sim_led green:status associated_usb 8-1 default_metric 10
	;;
mt7981,stx1170-gsw)
	ucidef_add_qmodem_slot 5g_usb0 type usb slot 2-1 alias 5g_usb0 default_metric 10
	;;
esac

board_config_flush

exit 0
