#!/bin/sh /etc/rc.common
START=99
STOP=13
USE_PROCD=1
service="$(basename ${basescript:-$initscript})"
. $IPKG_INSTROOT/lib/functions.sh
service_triggers()
{
	procd_add_reload_trigger "qmodem"

}

start_service(){
    _start_instances
}

stop_service(){
    _stop_instances
}

reload_service()
{
    stop
    start
}

_start_instances(){
    config_load qmodem
    config_foreach _start_instance modem-device
}

_stop_instances(){
    config_load qmodem
    config_foreach _stop_instance modem-device
}

_start_instance(){
    local Modem_ID
    Modem_ID=$1
    config_load qmodem
    config_get enabled $Modem_ID monitor_enabled 0
    [ "$enabled" != "1" ] && return 0
    config_get m_method $Modem_ID monitor_method
    config_get interval $Modem_ID monitor_interval 15
    config_get threshold $Modem_ID monitor_threshold 10
    config_get ping_type $Modem_ID monitor_ping_type
    config_get ping_dest $Modem_ID monitor_ping_dest
    config_get ping_ip_version $Modem_ID monitor_ping_ip_version
    config_get http_url $Modem_ID monitor_http_url
    procd_open_instance "m_$Modem_ID"
    procd_set_param command /usr/share/qmodem/modem_monitor.sh
    procd_append_param command --modem_id "$Modem_ID"
    procd_append_param command --method "$m_method"
    procd_append_param command --interval "$interval"
    procd_append_param command --threshold "$threshold"
    [ -n "$ping_type" ] && procd_append_param command --ping-type "$ping_type"
    [ -n "$ping_dest" ] && procd_append_param command --ping-dest "$ping_dest"
    [ -n "$ping_ip_version" ] && procd_append_param command --ping-ip-version "$ping_ip_version"
    [ -n "$http_url" ] && procd_append_param command --http-url "$http_url"
    procd_close_instance

}

_stop_instance(){
    :
}
