#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99
STOP=01

start_service() {
    procd_open_instance
    procd_set_param command "/usr/bin/autoip" "start27"
    procd_set_param respawn ${respawn_threshold:-2600000} ${respawn_timeout:-5} ${respawn_retry:-3600}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/autoip.pid
    procd_close_instance
}

stop_service() {
    /usr/bin/autoip stop27
}
