#!/bin/sh /etc/rc.common
START=99

restart(){                                                                                                       
	# sendat 2 "AT+CFUN=1,1"
  modem_init
	#/usr/share/modem/rm520n.sh &
}

start(){
  modem_init
	#/usr/share/modem/rm520n.sh &
   
}

printMsg() {
    local msg="$1"
    logger -t "${PROGRAM}" "${msg}"
} #日志输出调用API


modem_init(){

  ipcheckLOCKFILE="/tmp/ipcheck.lock"
  # Check if lockfile exists
  if [ -f $ipcheckLOCKFILE ]; then
      OLD_PID=$(cat $ipcheckLOCKFILE)
      echo "$(date): Kill $OLD_PID" 
      kill $OLD_PID
  fi
    lock_file="/tmp/moduleInit.lock"

    if [ -e "$lock_file" ]; then
    # 锁文件存在，获取锁定的进程 ID，并终止它
    locked_pid=$(cat "$lock_file")
        if [ -n "$locked_pid" ]; then
            echo "Terminating existing moduleInit process (PID: $locked_pid)..." >>/tmp/moduleInit
            kill "$locked_pid"
            sleep 2  # 等待一段时间确保进程终止
        fi
    fi
     
      Modem_Enable=`uci -q get modem.@ndis[0].enable` || Modem_Enable=1
      #模块启动
      #模块开关
      if [ "$Modem_Enable" == 0 ]; then
          echo 0 >/sys/class/gpio/cpe-pwr/value
          printMsg "禁用模块，退出"
          rm $lock_file
          exit 0
      else
          printMsg "模块启用"
          echo 1 >/sys/class/gpio/cpe-pwr/value
          check_and_update_simsel
          /usr/share/modem/rm520n.sh &
      fi
    
}

check_and_update_simsel() {
  local sim_slot=$(sendat 2 "AT+QUIMSLOT?" | grep '+QUIMSLOT:' | awk '{print $2}')
  local sim_sel_file="/etc/simsel"
  # 如果 sim_sel_file 不存在，则创建并写入外置卡 SIM 卡槽值，仅用于修正刷机和ui显示问题
  if [ ! -e "$sim_sel_file" ]; then
    printMsg "firstBoot"
    echo 1 > "$sim_sel_file"
    sendat 2 'AT+QMAP="mPDN_rule",0'
    sleep 5
    sendat 2 'AT+QMAP="mPDN_rule",0,1,0,1,1,"FF:FF:FF:FF:FF:FF"'
    sleep 8
    sendat 2 "AT+QUIMSLOT=1"
  fi
}



