#!/bin/sh
uci -q batch << EOF
	delete firewall.qmodem_ttl
	set firewall.qmodem_ttl=include
	set firewall.qmodem_ttl.type=script
	set firewall.qmodem_ttl.path=/etc/firewall.d/qmodem_ttl
	set firewall.qmodem_ttl.family=any
	set firewall.qmodem_ttl.reload=1
	commit firewall
EOF
uci -q batch <<-EOF >/dev/null
    delete ucitrack.@qmodem_ttl[-1]
	add ucitrack qmodem_ttl
	set ucitrack.@qmodem_ttl[-1].init=qmodem_ttl
	commit ucitrack
EOF

exit 0
