include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-athena-led
LUCI_TITLE:=LuCI Support for athena-led
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_VERSION:=20241029

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
